# Generated by Django 4.1.3 on 2022-12-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_infraction_last_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='jump_url_text',
            field=models.CharField(default='', help_text='The formatted jump url to message invoking the infraction.', max_length=102),
        ),
    ]
