# Generated by Django 4.1.4 on 2022-12-31 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_add_thread_id_to_nominations'),
        ('api', '0085_infraction_jump_url_text'),
    ]

    operations = [
    ]
